// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/flight_service.proto

package flightpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlightStatus int32

const (
	FlightStatus_FLIGHT_STATUS_UNSPECIFIED FlightStatus = 0
	FlightStatus_FLIGHT_STATUS_SCHEDULED   FlightStatus = 1
	FlightStatus_FLIGHT_STATUS_DELAYED     FlightStatus = 2
	FlightStatus_FLIGHT_STATUS_CANCELLED   FlightStatus = 3
)

// Enum value maps for FlightStatus.
var (
	FlightStatus_name = map[int32]string{
		0: "FLIGHT_STATUS_UNSPECIFIED",
		1: "FLIGHT_STATUS_SCHEDULED",
		2: "FLIGHT_STATUS_DELAYED",
		3: "FLIGHT_STATUS_CANCELLED",
	}
	FlightStatus_value = map[string]int32{
		"FLIGHT_STATUS_UNSPECIFIED": 0,
		"FLIGHT_STATUS_SCHEDULED":   1,
		"FLIGHT_STATUS_DELAYED":     2,
		"FLIGHT_STATUS_CANCELLED":   3,
	}
)

func (x FlightStatus) Enum() *FlightStatus {
	p := new(FlightStatus)
	*p = x
	return p
}

func (x FlightStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlightStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_flight_service_proto_enumTypes[0].Descriptor()
}

func (FlightStatus) Type() protoreflect.EnumType {
	return &file_proto_flight_service_proto_enumTypes[0]
}

func (x FlightStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlightStatus.Descriptor instead.
func (FlightStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_flight_service_proto_rawDescGZIP(), []int{0}
}

type Flight struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FlightNumber   string                 `protobuf:"bytes,2,opt,name=flight_number,json=flightNumber,proto3" json:"flight_number,omitempty"`
	Airline        string                 `protobuf:"bytes,3,opt,name=airline,proto3" json:"airline,omitempty"`
	Origin         string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination    string                 `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	DepartureTime  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ArrivalTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	TotalSeats     int32                  `protobuf:"varint,8,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,9,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	Price          float64                `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`
	Status         FlightStatus           `protobuf:"varint,11,opt,name=status,proto3,enum=flight.FlightStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Flight) Reset() {
	*x = Flight{}
	mi := &file_proto_flight_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flight) ProtoMessage() {}

func (x *Flight) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flight.ProtoReflect.Descriptor instead.
func (*Flight) Descriptor() ([]byte, []int) {
	return file_proto_flight_service_proto_rawDescGZIP(), []int{0}
}

func (x *Flight) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Flight) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *Flight) GetAirline() string {
	if x != nil {
		return x.Airline
	}
	return ""
}

func (x *Flight) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Flight) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Flight) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *Flight) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

func (x *Flight) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *Flight) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

func (x *Flight) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Flight) GetStatus() FlightStatus {
	if x != nil {
		return x.Status
	}
	return FlightStatus_FLIGHT_STATUS_UNSPECIFIED
}

type SearchFlightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	DepartureDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFlightsRequest) Reset() {
	*x = SearchFlightsRequest{}
	mi := &file_proto_flight_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFlightsRequest) ProtoMessage() {}

func (x *SearchFlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFlightsRequest.ProtoReflect.Descriptor instead.
func (*SearchFlightsRequest) Descriptor() ([]byte, []int) {
	return file_proto_flight_service_proto_rawDescGZIP(), []int{1}
}

func (x *SearchFlightsRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SearchFlightsRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SearchFlightsRequest) GetDepartureDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureDate
	}
	return nil
}

type SearchFlightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flights       []*Flight              `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFlightsResponse) Reset() {
	*x = SearchFlightsResponse{}
	mi := &file_proto_flight_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFlightsResponse) ProtoMessage() {}

func (x *SearchFlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFlightsResponse.ProtoReflect.Descriptor instead.
func (*SearchFlightsResponse) Descriptor() ([]byte, []int) {
	return file_proto_flight_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchFlightsResponse) GetFlights() []*Flight {
	if x != nil {
		return x.Flights
	}
	return nil
}

type GetFlightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      int64                  `protobuf:"varint,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlightRequest) Reset() {
	*x = GetFlightRequest{}
	mi := &file_proto_flight_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightRequest) ProtoMessage() {}

func (x *GetFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightRequest.ProtoReflect.Descriptor instead.
func (*GetFlightRequest) Descriptor() ([]byte, []int) {
	return file_proto_flight_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetFlightRequest) GetFlightId() int64 {
	if x != nil {
		return x.FlightId
	}
	return 0
}

type GetFlightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flight        *Flight                `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlightResponse) Reset() {
	*x = GetFlightResponse{}
	mi := &file_proto_flight_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlightResponse) ProtoMessage() {}

func (x *GetFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlightResponse.ProtoReflect.Descriptor instead.
func (*GetFlightResponse) Descriptor() ([]byte, []int) {
	return file_proto_flight_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetFlightResponse) GetFlight() *Flight {
	if x != nil {
		return x.Flight
	}
	return nil
}

type ReserveSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      int64                  `protobuf:"varint,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	Seats         int32                  `protobuf:"varint,2,opt,name=seats,proto3" json:"seats,omitempty"`
	ReservationId string                 `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatsRequest) Reset() {
	*x = ReserveSeatsRequest{}
	mi := &file_proto_flight_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatsRequest) ProtoMessage() {}

func (x *ReserveSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatsRequest.ProtoReflect.Descriptor instead.
func (*ReserveSeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_flight_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveSeatsRequest) GetFlightId() int64 {
	if x != nil {
		return x.FlightId
	}
	return 0
}

func (x *ReserveSeatsRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *ReserveSeatsRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ReserveSeatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RemainingSeats int32                  `protobuf:"varint,2,opt,name=remaining_seats,json=remainingSeats,proto3" json:"remaining_seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveSeatsResponse) Reset() {
	*x = ReserveSeatsResponse{}
	mi := &file_proto_flight_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatsResponse) ProtoMessage() {}

func (x *ReserveSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatsResponse.ProtoReflect.Descriptor instead.
func (*ReserveSeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_flight_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveSeatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveSeatsResponse) GetRemainingSeats() int32 {
	if x != nil {
		return x.RemainingSeats
	}
	return 0
}

type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      int64                  `protobuf:"varint,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Seats         int32                  `protobuf:"varint,3,opt,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_proto_flight_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_flight_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseReservationRequest) GetFlightId() int64 {
	if x != nil {
		return x.FlightId
	}
	return 0
}

func (x *ReleaseReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseReservationRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

type ReleaseReservationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,2,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseReservationResponse) Reset() {
	*x = ReleaseReservationResponse{}
	mi := &file_proto_flight_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationResponse) ProtoMessage() {}

func (x *ReleaseReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_flight_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseReservationResponse) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

var File_proto_flight_service_proto protoreflect.FileDescriptor

const file_proto_flight_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/flight_service.proto\x12\x06flight\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x03\n" +
	"\x06Flight\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rflight_number\x18\x02 \x01(\tR\fflightNumber\x12\x18\n" +
	"\aairline\x18\x03 \x01(\tR\aairline\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x05 \x01(\tR\vdestination\x12A\n" +
	"\x0edeparture_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureTime\x12=\n" +
	"\farrival_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\varrivalTime\x12\x1f\n" +
	"\vtotal_seats\x18\b \x01(\x05R\n" +
	"totalSeats\x12'\n" +
	"\x0favailable_seats\x18\t \x01(\x05R\x0eavailableSeats\x12\x14\n" +
	"\x05price\x18\n" +
	" \x01(\x01R\x05price\x12,\n" +
	"\x06status\x18\v \x01(\x0e2\x14.flight.FlightStatusR\x06status\"\x93\x01\n" +
	"\x14SearchFlightsRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12A\n" +
	"\x0edeparture_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureDate\"A\n" +
	"\x15SearchFlightsResponse\x12(\n" +
	"\aflights\x18\x01 \x03(\v2\x0e.flight.FlightR\aflights\"/\n" +
	"\x10GetFlightRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\x03R\bflightId\";\n" +
	"\x11GetFlightResponse\x12&\n" +
	"\x06flight\x18\x01 \x01(\v2\x0e.flight.FlightR\x06flight\"o\n" +
	"\x13ReserveSeatsRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\x03R\bflightId\x12\x14\n" +
	"\x05seats\x18\x02 \x01(\x05R\x05seats\x12%\n" +
	"\x0ereservation_id\x18\x03 \x01(\tR\rreservationId\"Y\n" +
	"\x14ReserveSeatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fremaining_seats\x18\x02 \x01(\x05R\x0eremainingSeats\"u\n" +
	"\x19ReleaseReservationRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\x03R\bflightId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x14\n" +
	"\x05seats\x18\x03 \x01(\x05R\x05seats\"_\n" +
	"\x1aReleaseReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0favailable_seats\x18\x02 \x01(\x05R\x0eavailableSeats*\x82\x01\n" +
	"\fFlightStatus\x12\x1d\n" +
	"\x19FLIGHT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FLIGHT_STATUS_SCHEDULED\x10\x01\x12\x19\n" +
	"\x15FLIGHT_STATUS_DELAYED\x10\x02\x12\x1b\n" +
	"\x17FLIGHT_STATUS_CANCELLED\x10\x032\xc7\x02\n" +
	"\rFlightService\x12L\n" +
	"\rSearchFlights\x12\x1c.flight.SearchFlightsRequest\x1a\x1d.flight.SearchFlightsResponse\x12@\n" +
	"\tGetFlight\x12\x18.flight.GetFlightRequest\x1a\x19.flight.GetFlightResponse\x12I\n" +
	"\fReserveSeats\x12\x1b.flight.ReserveSeatsRequest\x1a\x1c.flight.ReserveSeatsResponse\x12[\n" +
	"\x12ReleaseReservation\x12!.flight.ReleaseReservationRequest\x1a\".flight.ReleaseReservationResponseB\x1fZ\x1dflight-service/proto;flightpbb\x06proto3"

var (
	file_proto_flight_service_proto_rawDescOnce sync.Once
	file_proto_flight_service_proto_rawDescData []byte
)

func file_proto_flight_service_proto_rawDescGZIP() []byte {
	file_proto_flight_service_proto_rawDescOnce.Do(func() {
		file_proto_flight_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flight_service_proto_rawDesc), len(file_proto_flight_service_proto_rawDesc)))
	})
	return file_proto_flight_service_proto_rawDescData
}

var file_proto_flight_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_flight_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_flight_service_proto_goTypes = []any{
	(FlightStatus)(0),                  // 0: flight.FlightStatus
	(*Flight)(nil),                     // 1: flight.Flight
	(*SearchFlightsRequest)(nil),       // 2: flight.SearchFlightsRequest
	(*SearchFlightsResponse)(nil),      // 3: flight.SearchFlightsResponse
	(*GetFlightRequest)(nil),           // 4: flight.GetFlightRequest
	(*GetFlightResponse)(nil),          // 5: flight.GetFlightResponse
	(*ReserveSeatsRequest)(nil),        // 6: flight.ReserveSeatsRequest
	(*ReserveSeatsResponse)(nil),       // 7: flight.ReserveSeatsResponse
	(*ReleaseReservationRequest)(nil),  // 8: flight.ReleaseReservationRequest
	(*ReleaseReservationResponse)(nil), // 9: flight.ReleaseReservationResponse
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
}
var file_proto_flight_service_proto_depIdxs = []int32{
	10, // 0: flight.Flight.departure_time:type_name -> google.protobuf.Timestamp
	10, // 1: flight.Flight.arrival_time:type_name -> google.protobuf.Timestamp
	0,  // 2: flight.Flight.status:type_name -> flight.FlightStatus
	10, // 3: flight.SearchFlightsRequest.departure_date:type_name -> google.protobuf.Timestamp
	1,  // 4: flight.SearchFlightsResponse.flights:type_name -> flight.Flight
	1,  // 5: flight.GetFlightResponse.flight:type_name -> flight.Flight
	2,  // 6: flight.FlightService.SearchFlights:input_type -> flight.SearchFlightsRequest
	4,  // 7: flight.FlightService.GetFlight:input_type -> flight.GetFlightRequest
	6,  // 8: flight.FlightService.ReserveSeats:input_type -> flight.ReserveSeatsRequest
	8,  // 9: flight.FlightService.ReleaseReservation:input_type -> flight.ReleaseReservationRequest
	3,  // 10: flight.FlightService.SearchFlights:output_type -> flight.SearchFlightsResponse
	5,  // 11: flight.FlightService.GetFlight:output_type -> flight.GetFlightResponse
	7,  // 12: flight.FlightService.ReserveSeats:output_type -> flight.ReserveSeatsResponse
	9,  // 13: flight.FlightService.ReleaseReservation:output_type -> flight.ReleaseReservationResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_flight_service_proto_init() }
func file_proto_flight_service_proto_init() {
	if File_proto_flight_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flight_service_proto_rawDesc), len(file_proto_flight_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_flight_service_proto_goTypes,
		DependencyIndexes: file_proto_flight_service_proto_depIdxs,
		EnumInfos:         file_proto_flight_service_proto_enumTypes,
		MessageInfos:      file_proto_flight_service_proto_msgTypes,
	}.Build()
	File_proto_flight_service_proto = out.File
	file_proto_flight_service_proto_goTypes = nil
	file_proto_flight_service_proto_depIdxs = nil
}
